version: "3"
services:
  db:
    image: postgres:13
    container_name: db
    restart: always
    ports:
      - 2345:5432
    env_file:
      - .env
    networks:
      - my-network
    volumes:
      - postgres:/var/lib/postgresql/data

  node_app:
    container_name: node_app
    build: .
    ports:
      - 4000:4000
    depends_on:
      - db
    networks:
      - my-network
    env_file:
      - .env
volumes:
  postgres:

networks:
  my-network:
    external: true
